# Generated by Django 3.0.7 on 2020-06-21 13:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('master', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Need',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(max_length=1000, verbose_name='投稿内容')),
                ('is_passed', models.BooleanField(default=False, verbose_name='審査済みフラグ')),
                ('occupation_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='master.Occupation')),
            ],
        ),
    ]
