# Generated by Django 3.0.7 on 2020-06-21 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('needs', '0002_need_user_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='need',
            name='username',
            field=models.CharField(default='', max_length=255, verbose_name='ニックネーム'),
            preserve_default=False,
        ),
    ]
