# Generated by Django 3.0.5 on 2020-07-11 12:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('needs', '0003_need_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='need',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2020, 7, 11, 21, 9, 8, 505169), verbose_name='投稿日時'),
        ),
    ]
