# Generated by Django 3.0.5 on 2020-08-02 09:50

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('needs', '0004_need_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='need',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2020, 8, 2, 18, 50, 40, 988609), verbose_name='投稿日時'),
        ),
    ]
