# Generated by Django 3.0.5 on 2020-08-02 10:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('needs', '0005_auto_20200802_1850'),
    ]

    operations = [
        migrations.AlterField(
            model_name='need',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2020, 8, 2, 19, 5, 24, 384802), verbose_name='投稿日時'),
        ),
    ]
