# Generated by Django 3.0.5 on 2020-08-09 10:26

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('needs', '0008_auto_20200802_1912'),
    ]

    operations = [
        migrations.AlterField(
            model_name='need',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2020, 8, 9, 19, 26, 48, 969246), verbose_name='投稿日時'),
        ),
    ]
