# Generated by Django 3.0.5 on 2020-08-09 12:12

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('needs', '0010_auto_20200809_2109'),
    ]

    operations = [
        migrations.AlterField(
            model_name='need',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2020, 8, 9, 21, 12, 5, 60916), verbose_name='投稿日時'),
        ),
    ]
