# Generated by Django 3.0.5 on 2020-08-09 12:13

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('needs', '0011_auto_20200809_2112'),
    ]

    operations = [
        migrations.AlterField(
            model_name='need',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2020, 8, 9, 21, 13, 48, 709374), verbose_name='投稿日時'),
        ),
    ]
