# Generated by Django 3.0.5 on 2020-08-09 12:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('needs', '0013_auto_20200809_2133'),
    ]

    operations = [
        migrations.AlterField(
            model_name='need',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2020, 8, 9, 21, 33, 37, 555804), verbose_name='投稿日時'),
        ),
    ]
