# Generated by Django 3.0.5 on 2020-08-09 12:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0001_initial'),
        ('user', '0006_auto_20200802_1912'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='occupation_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='master.Occupation'),
        ),
    ]
